module Full_adder_tb();
  reg a; 
  reg b;
  reg cin;
  wire sum;
	wire cout;
  Full_Adder dut(.a(a),.b(b),.cin(cin),.sum(sum),.cout(cout));
 initial begin
  $dumpfile("wave.vcd"); 
   $dumpvars(0,Full_adder_tb);  
end
 
  initial 
	begin
      a=0; b=0; cin=0; #10
      a=0; b=0; cin=1; #10
      a=0; b=1; cin=0; #10
      a=0; b=1; cin=1; #10
      a=1; b=0; cin=0; #10
      a=1; b=0; cin=1; #10
      a=1; b=1; cin=0; #10
      a=1; b=1; cin=1; #10
      $finish;
     end
endmodule
